In [1]:
#Import Important Python Libraries
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
import time
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
#Create a Function for Driver, in this We Call the Chrome Browser and Maximize the window
def Setup_Driver():
    Driver = webdriver.Chrome()
    Driver.maximize_window()
    return Driver

In [3]:
#Scrap the Data and Store in Variables List
#----------------------------------------------------

Driver = Setup_Driver() #Call the Setup_Driver Function, that we Created Before
Driver.get("https://www.instahyre.com/python-jobs") #Store Website URL in Driver Variable, We Extract the Data from this URL

time.sleep(5) #Sleep is important to Optimize the System

    #Create Variables List, Where We Append our Data that We will Extract from WebSite
Name_List = []
Location_List = []
Found_List = []
Employees_List = []
About_List = []
Skills_List = []
Links_List = []

    #Run a Loop so that We Extract the Data of Multiple Pages.
for i in range(1,51):
    #By Using Xpath, We Store Particular path in Particular Variable like "Name"
    Name = Driver.find_elements("xpath","//div[@class='employer-details col-md-10 col-sm-8 col-xs-10']/a/div/div")
    Location = Driver.find_elements("xpath","//div[@class='employer-details col-md-10 col-sm-8 col-xs-10']/a//div[@class='employer-locations']/span[@class='info ng-scope']")
    Found = Driver.find_elements("xpath","//div[@class='employer-details col-md-10 col-sm-8 col-xs-10']//div[@class='employer-info']/span[1]")
    Employees = Driver.find_elements("xpath","//div[@class='employer-details col-md-10 col-sm-8 col-xs-10']//div[@class='employer-info']//span[@class='ng-scope'][2]")
    About = Driver.find_elements("xpath","//div[@class='employer-details col-md-10 col-sm-8 col-xs-10']//div[@class='employer-notes ng-binding ng-scope']")
    Skills = Driver.find_elements("xpath","//div[@class='employer-details col-md-10 col-sm-8 col-xs-10']//div[@class='job-skills ng-scope']")
    Links = Driver.find_elements("xpath","//div[@class='employer-details-mobile col-xs-10']/a")

    #Run a Loop, so that one by one our text Data Append on Variables that we Created Before
    #We Use Try and Except Function, So if There is nothing to Append, it append "Error" String. At The End our Lenght of List Will match
    for j in range(len(Name)):
        try:
            Name_ = Name[j].text
            Name_List.append(Name_)
        except Exception:
            Name_List.append("Error")
          
        try:
            Location_ = Location[j].text
            Location_List.append(Location_)
        except Exception:
            Location_List.append("Error")

        try:
            Founds_ = Found[j].text
            Found_List.append(Founds_)
        except Exception:
            Found_List.append("Error")
        
        try:
            Employee_ = Employees[j].text
            Employees_List.append(Employee_)
        except Exception:
            Employees_List.append("Error")

        try:
            About_ = About[j].text
            About_List.append(About_)
        except Exception:
            About_List.append("Error")

        try:
            Skills_ = Skills[j].text
            Skills_List.append(Skills_)
        except Exception:
            Skills_List.append("Error")

        try:
            Links_ = Links[j].get_attribute("href")
            Links_List.append(Links_)
        except Exception:
            Links_List.append("Error")

    #By using Click Function, We Move From one page to Another page
    element = Driver.find_element("xpath","//div[@class='pagination ng-scope']//li[12]") #Path of NEXT Button
    element.click()

    time.sleep(5)

Driver.close() #When all the Data is Extacted, we Close the Chrome Window.

In [4]:
#Create the DataFrame Using Pandas and Store all the Data in DataFrame
Data = []
Data = pd.DataFrame(Data)
Data["Name"] = Name_List
Data["Location"] = Location_List
Data["Founded"] = Found_List
Data["Employees"] = Employees_List
Data["About"] = About_List
Data["Skills"] = Skills_List
Data["Link"] = Links_List

#Now Identifying Where and What is Wrong in Data
#print(Data)

In [5]:
#Cleaning The Data
#--------------------------------

    #as We Remember that in upper Syntax we append "Error" String if these was any missing values
Error = Data[Data.eq("Error").any(axis=1)]  #From this Syntax We can Get to know that in which column and how many "Errors" entry are there
                                            #only Data["About"] column have "Error" Values

    #Delete the Rows where Data Values are "Error"
Data = Data[Data["About"] != "Error"]

#12 Rows Deleted Successfully

In [31]:
Data.to_csv("D:/DA/.DataNewSet.csv",index=False)

In [16]:
Data["Founded"] = Data["Founded"].str.replace("Founded in","")

In [18]:
Data["Founded"].unique()

array([' 2008', ' 2017', ' 2002', ' 1983', ' 2012', ' 2007', ' 2015',
       ' 2014', ' 2019', ' 2011', ' 1986', ' 2023', ' 2020', ' 1852',
       ' 2021', ' 1988', ' 2013', ' 2003', ' 2016', ' 2022', ' 2018',
       ' 1987', ' 2006', ' 1973', ' 2009', ' 2000', ' 1887', ' 1925',
       ' 2004', ' 2010', ' 2001', ' 1982', ' 1903', ' 1998', ' 1992',
       ' 1994', ' 1989', ' 1900', ' 1984', ' 1999', ' 1876', ' 1981',
       ' 1995', ' 1996', ' 1993', ' 1990', ' 1997', ' 2005', ' 1976',
       ' 1971', ' 1960', ' 1962', ' 1975', ' 2024', ' 1985', ' 1886',
       ' 1967', ' 1972', ' 1945', ' 1873', ' 1904', ' 1968', ' 1865'],
      dtype=object)

In [22]:
Data["Employees"] = Data["Employees"].str.replace("employees","")

In [24]:
Data["Employees"].unique()

array(['500 - 1000 ', '10 - 50 ', '50 - 200 ', 'More than 1000 ',
       '200 - 500 ', '0 - 10 '], dtype=object)

In [25]:
Data["Skills"] = Data["Skills"].str.replace("\n",",")

In [ ]:
Data["Location"] = Data["Location"].str.replace("Job available in","")

In [26]:
Data

,Name,Location,Founded,Employees,About,Skills,Link
0,Aakash Edutech - Data Scientist,Job available in Gurgaon,2008,500 - 1000,Aakash Digital is an e-learning platform intro...,PythonMachine LearningNLPComputer Vision,https://www.instahyre.com/job-306720-data-scie...
1,Aakash Edutech - Data Scientist,Job available in Pune,2008,500 - 1000,Aakash Digital is an e-learning platform intro...,PythonMachine LearningNLPData Structures,https://www.instahyre.com/job-306717-data-scie...
2,Accrete.AI - Senior Engineering Manager,Job available in Mumbai,2017,10 - 50,Accrete.AI is a Computer Software company that...,PythonAWSMongoDBDevOps,https://www.instahyre.com/job-306704-senior-en...
3,Brevan Howard - Senior Backend Engineer,Job available in Bangalore,2002,500 - 1000,Brevan Howard is an alternative investment man...,PythonAWSpytestDockerKubernetes,https://www.instahyre.com/job-306559-senior-ba...
4,Intellectyx Data Science - Senior Python Devel...,Job available in Bangalore,2008,50 - 200,Intellectyx is a Software Services Company tha...,PythonFlaskDocker,https://www.instahyre.com/job-306728-senior-py...
...,...,...,...,...,...,...,...
995,Tredence Inc - Consultant L2,Job available in Gurgaon,2013,500 - 1000,Tredence Inc is a Management Consulting compan...,PythonETLSQLDatabricksHadoop,https://www.instahyre.com/job-297463-consultan...
996,Uber - Automation Analyst,Job available in Bangalore,2009,More than 1000,Uber offers an online-ride hailing and on-dema...,PythonAPI TestingSQLAutomation Testing,https://www.instahyre.com/job-297539-automatio...
997,Unify - Data Toolings,Job available in Work From Home,2014,More than 1000,Unify is a software development company. Has o...,PythonJavaScript,https://www.instahyre.com/job-297475-data-tool...
998,Wayfair - Staff Engineer - SRE,Job available in Bangalore,2002,More than 1000,Wayfair is the online destination for the home...,PythonDevOpsJavaCloud Security,https://www.instahyre.com/job-297624-staff-eng...
999,Zepto - Senior Software Engineer - ML Platform,Job available in Bangalore,2021,More than 1000,Zepto is an online grocery delivery platform t...,PythonComputer VisionMachine LearningRPyTorch+2,https://www.instahyre.com/job-297566-senior-so...